apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: property-management
spec:
  selector:
    app: property-management-api
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort