apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: property-management
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/property_db"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_JPA_SHOW_SQL: "true"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "validate"